NAME = test

CC = gcc
CFLAGS = -Wall -Wextra -Werror

# miniLibX
MLX_PATH = minilibx-linux/
MLX_NAME = libmlx.a
MLX = $(MLX_PATH)$(MLX_NAME)

# Includes
INC = -I./\
	  -I./minilibx-linux/

# Sources
SRC_PATH = ./
SRC = 